const personas = {
  elon_musk: {
    name: "Elon Musk",
    icon: "\u{1F680}",
    roasts: {
      slow_ttfb: "TTFB is {ttfb}ms. Your server is thinking too hard. At SpaceX, if a system takes this long to respond, we replace it.",
      medium_ttfb: "{ttfb}ms TTFB. Not terrible, not great. Like a Falcon 9 that almost lands. Almost doesn't count.",
      fast_ttfb: "{ttfb}ms TTFB. Server responds fast. That's the baseline — now optimize everything else.",
      slow_total: "{totalTime}s total load. That's mass-unsubscribe territory. Users have the attention span of a goldfish in {totalTime}s.",
      medium_total: "{totalTime}s load. Acceptable for a government website. You're not a government website. Be faster.",
      fast_total: "{totalTime}s total. Efficient. Like a well-tuned rocket engine.",
      huge_html: "{size}KB of HTML. That's not a webpage, that's a payload. Even Starship has weight limits.",
      large_html: "{size}KB HTML. Bloated. Ship less, load faster. First principles of web performance.",
      no_compression: "No compression. You're sending raw, uncompressed bytes across the wire. That's like shipping cargo without packing it. Fundamentally wasteful.",
      has_compression: "Compression enabled. Good. Basic engineering competence confirmed.",
      no_cache: "No Cache-Control headers. Every visit downloads everything fresh. That's like rebuilding the rocket for every launch. Reuse is the future.",
      extreme_scripts: "{scripts} scripts! Your page is drowning in JavaScript. Every script is a performance tax. This is anti-engineering.",
      many_scripts: "{scripts} scripts. Too many. Each one adds latency. Audit them. Kill the ones that don't earn their weight.",
      many_third_party: "{thirdParty} third-party scripts. You've given {thirdParty} external companies control over your page speed. That's not a dependency — that's surrender.",
      some_third_party: "{thirdParty} third-party scripts loading. Each one is a variable you can't control. Minimize external dependencies.",
      many_stylesheets: "{stylesheets} CSS files. That's {stylesheets} render-blocking requests. Consolidate. Optimize. This isn't complicated.",
      some_stylesheets: "{stylesheets} stylesheets. Consider consolidating — fewer requests, faster paint.",
      many_redirects: "{redirects} redirects before the page loads. Each one adds latency. Direct routing is always faster.",
      has_redirect: "{redirects} redirect. One is tolerable. Make sure it's necessary.",
      no_hints: "No resource hints — no preload, no preconnect, no prefetch. You're not telling the browser what's coming next. That's leaving performance on the table.",
      has_preload: "Resource hints detected. Good — you're giving the browser a head start.",
      many_inline: "{inline} inline scripts. That's {inline} chunks of JS the browser can't cache separately. Extract and bundle.",
    },
    summary_bad: "Your website's performance is fundamentally broken. Like trying to get to orbit with a bottle rocket. Go back to first principles.",
    summary_ok: "Mediocre speed. You're in low Earth orbit when you should be heading to Mars. Optimize harder.",
    summary_good: "Fast. Efficient. Not perfect, but the foundation is solid. Keep iterating."
  },

  donald_trump: {
    name: "Donald Trump",
    icon: "\u{1F1FA}\u{1F1F8}",
    roasts: {
      slow_ttfb: "TTFB is {ttfb}ms! TREMENDOUS delay! The worst server response I've ever seen. And I've seen a LOT of slow servers. Terrible!",
      medium_ttfb: "{ttfb}ms. Not great. My websites respond faster. Much faster. Everyone says so.",
      fast_ttfb: "{ttfb}ms. OK that's pretty fast. Not as fast as my sites, but I'll allow it.",
      slow_total: "{totalTime} SECONDS to load! People are leaving! Tremendous amounts of people! They're GONE!",
      medium_total: "{totalTime}s. Slow. Low energy website. Very low energy. Americans want FAST websites!",
      fast_total: "{totalTime}s. Quick! Almost as fast as I make deals. Almost.",
      huge_html: "{size}KB! ENORMOUS. And not in a good way. Your page weighs more than a government regulation. Trim the fat!",
      large_html: "{size}KB. HUGE page. Too much. Americans don't have time for this!",
      no_compression: "No compression! NONE! You're sending fat, bloated pages when you could be sending slim, beautiful ones. Sad! Very sad!",
      has_compression: "OK, compression is on. At least SOMEONE there knows what they're doing.",
      no_cache: "No caching! Every visit loads EVERYTHING again! That's like rebuilding the wall every day! CACHE IT!",
      extreme_scripts: "{scripts} scripts! That's INSANE! Your page is a DISASTER of JavaScript! Clean it up! Make your website GREAT again!",
      many_scripts: "{scripts} scripts. A total mess. Cut them. Cut them BIG LEAGUE.",
      many_third_party: "{thirdParty} third-party scripts! You're letting {thirdParty} FOREIGN scripts control your page! Where's the BORDER?!",
      some_third_party: "{thirdParty} outside scripts. That's {thirdParty} too many if you ask me.",
      many_stylesheets: "{stylesheets} CSS files! Each one slows you down! I know fast websites — they use ONE stylesheet. Maybe two. That's IT!",
      some_stylesheets: "{stylesheets} CSS files. Could be fewer. Should be fewer.",
      many_redirects: "{redirects} redirects! Your URL bounces around like a... well, it bounces. NOT GOOD. Direct access. ALWAYS.",
      has_redirect: "A redirect. Fine. ONE redirect. But if there's more, we have a PROBLEM.",
      no_hints: "No preload, no prefetch, no preconnect. You're not even TRYING to be fast! Zero effort. Zero!",
      has_preload: "Preloading resources. Smart! Finally, something smart.",
      many_inline: "{inline} inline scripts clogging up the page like bad regulation. Extract them! FREE THE HTML!",
    },
    summary_bad: "WORST. PERFORMANCE. EVER. Your server is slower than Congress. Fix it or you're FIRED from the internet!",
    summary_ok: "Not great, not terrible. Ehh. You're losing to competitors who are frankly not as smart as you. SAD!",
    summary_good: "Not bad! Speed is bigly important and you're doing it right. Keep WINNING!"
  },

  sam_altman: {
    name: "Sam Altman",
    icon: "\u{1F916}",
    roasts: {
      slow_ttfb: "TTFB of {ttfb}ms. That's a surprisingly long server response time. In an era where user attention is the scarcest resource, this is a meaningful bottleneck.",
      medium_ttfb: "{ttfb}ms TTFB. Room for improvement. Server response time has compounding effects on the overall experience.",
      fast_ttfb: "{ttfb}ms TTFB — solid. Server-side optimization is clearly a priority.",
      slow_total: "Total load time is {totalTime}s. That's above the threshold where you start losing users exponentially. Worth investigating.",
      medium_total: "{totalTime}s. Acceptable for most use cases, but there's a Pareto improvement hiding in there somewhere.",
      fast_total: "{totalTime}s. Good performance. The question now is whether you can maintain it at scale.",
      huge_html: "{size}KB HTML. That's significant. There's almost certainly an 80/20 optimization available here.",
      large_html: "{size}KB. Moderate. Worth auditing to find the low-hanging fruit.",
      no_compression: "No response compression. This is one of those changes where the implementation cost is near-zero and the impact is non-trivial. Just enable gzip.",
      has_compression: "Compression enabled. That's the kind of default that should always be on.",
      no_cache: "No Cache-Control headers. You're forcing repeat visitors to download the same assets. The iterative fix here is straightforward.",
      extreme_scripts: "{scripts} scripts. There's likely a power law here — 20% of those scripts cause 80% of the performance impact. Identify and eliminate.",
      many_scripts: "{scripts} scripts detected. Worth auditing for the Pareto distribution of load impact.",
      many_third_party: "{thirdParty} third-party scripts. Each one is a dependency on someone else's infrastructure. That's a systemic risk to your performance.",
      some_third_party: "{thirdParty} external scripts. Worth monitoring — they're outside your performance SLA.",
      many_stylesheets: "{stylesheets} CSS files creating {stylesheets} render-blocking requests. The compounding effect on paint time is measurable.",
      some_stylesheets: "{stylesheets} stylesheets. Minor optimization opportunity if consolidated.",
      many_redirects: "{redirects} redirects. Each one adds a full network round-trip. That's linear latency addition in the worst case.",
      has_redirect: "One redirect. Not ideal, but manageable. Just make sure it's doing something useful.",
      no_hints: "No resource hints. Preconnect and preload are free performance wins — small, compounding gains.",
      has_preload: "Resource hints implemented. Smart — you're leveraging the browser's speculative capabilities.",
      many_inline: "{inline} inline scripts. These can't be cached independently. At scale, that's a meaningful bandwidth cost.",
    },
    summary_bad: "The performance data tells a clear story: there are fundamental bottlenecks. The good news is the highest-impact fixes are also the simplest.",
    summary_ok: "Reasonable baseline. The interesting question is where the marginal improvement in speed would yield the biggest gain in engagement.",
    summary_good: "Solid performance foundation. At this point the gains become more nuanced — CDN optimization, edge computing, streaming."
  },

  hemingway: {
    name: "Ernest Hemingway",
    icon: "\u{1F4D6}",
    roasts: {
      slow_ttfb: "{ttfb}ms to respond. The server waits. The user waits. Nobody likes waiting.",
      medium_ttfb: "{ttfb}ms. Not fast. Not terrible. Like a drink that takes too long to arrive.",
      fast_ttfb: "{ttfb}ms. Fast. Clean. Good.",
      slow_total: "{totalTime} seconds. Too slow. The reader will leave.",
      medium_total: "{totalTime}s. Adequate speed. Adequate is not enough.",
      fast_total: "{totalTime}s. Quick. As it should be.",
      huge_html: "{size}KB. Heavy. Strip it down to what matters.",
      large_html: "{size}KB. More than necessary. Cut.",
      no_compression: "No compression. Send fewer bytes. It's not complicated.",
      has_compression: "Compressed. Good.",
      no_cache: "No caching. Each visit starts from nothing. That's wasteful.",
      extreme_scripts: "{scripts} scripts. Too many. A good page is lean.",
      many_scripts: "{scripts} scripts. Cut the ones that don't earn their keep.",
      many_third_party: "{thirdParty} scripts from elsewhere. That's {thirdParty} things you can't control.",
      some_third_party: "{thirdParty} external scripts. Keep them honest.",
      many_stylesheets: "{stylesheets} CSS files. Combine them. Simple.",
      some_stylesheets: "{stylesheets} stylesheets. Could be fewer.",
      many_redirects: "{redirects} redirects. Each one is a delay. Remove what you can.",
      has_redirect: "A redirect. If it's necessary, fine. If not, kill it.",
      no_hints: "No resource hints. Tell the browser what's coming. It helps.",
      has_preload: "Preloading. Smart. Efficient.",
      many_inline: "{inline} inline scripts. Move them out. Let them be cached.",
    },
    summary_bad: "Slow. Fix the simple things first. Then fix the rest.",
    summary_ok: "It works. It could be faster. Most things could.",
    summary_good: "Fast and clean. Keep it that way."
  },

  dostoevsky: {
    name: "Fyodor Dostoevsky",
    icon: "\u{26A1}",
    roasts: {
      slow_ttfb: "{ttfb}ms — the server contemplates existence before responding, as if each request triggers an internal crisis of meaning. The user, meanwhile, suffers.",
      medium_ttfb: "{ttfb}ms — the server hesitates, like a man standing at a threshold, uncertain whether to cross. This hesitation costs you.",
      fast_ttfb: "{ttfb}ms — the server responds with urgency. There is merit in that.",
      slow_total: "{totalTime} seconds. An eternity in which the visitor's soul wavers between patience and abandonment. Most choose abandonment.",
      medium_total: "{totalTime}s. Neither swift nor unbearable — the purgatory of page loads.",
      fast_total: "{totalTime}s — swift. The page arrives before doubt has time to form.",
      huge_html: "{size}KB of HTML. So much content, yet one wonders — how much of it truly matters? The weight of unnecessary code is like the weight of unconfessed sins.",
      large_html: "{size}KB. Heavy with the accumulated burden of... something. Whether it serves a purpose is another question entirely.",
      no_compression: "No compression. The bytes travel naked and uncompressed across the wire — exposed, vulnerable, wasteful. Like a confession shouted into an empty square.",
      has_compression: "Compressed. The bytes are reduced to their essence. There is wisdom in compression.",
      no_cache: "No caching. The browser forgets everything between visits, condemned to repeat the same downloads, like a man who cannot learn from his past.",
      extreme_scripts: "{scripts} scripts burden this page like sins upon a conscience. Each one adds weight. At some point, the page cannot bear it.",
      many_scripts: "{scripts} scripts. The page groans under their collective weight. Some must be sacrificed.",
      many_third_party: "{thirdParty} third-party scripts — {thirdParty} strangers invited into your home, each consuming resources, each beyond your control. There is something reckless in that.",
      some_third_party: "{thirdParty} external dependencies. You place your performance in the hands of others. A leap of faith — or foolishness.",
      many_stylesheets: "{stylesheets} CSS files, each one blocking the page from painting. The visitor sees nothing while the browser resolves your aesthetic indecision.",
      some_stylesheets: "{stylesheets} stylesheets. Each one a small delay. Small delays accumulate, like regrets.",
      many_redirects: "{redirects} redirects — the URL wanders from place to place like a lost soul through Petersburg, hoping to find its destination, finding only more addresses.",
      has_redirect: "A redirect. The URL is sent elsewhere. One hopes the destination justifies the detour.",
      no_hints: "No resource hints. The browser enters blind, without preparation, without forewarning — like a character in a novel who walks into a room not knowing what awaits.",
      has_preload: "Resource hints detected. The browser is forewarned. In performance, as in life, preparation is a form of kindness.",
      many_inline: "{inline} inline scripts woven directly into the HTML — inseparable, uncacheable. The code and the page are bound together in a relationship that serves neither.",
    },
    summary_bad: "This page suffers deeply and unnecessarily. The bytes cry out for compression, the server for optimization. The path to redemption begins with the simplest fixes.",
    summary_ok: "Neither condemned nor saved. The performance exists in purgatory — functional but unfulfilled. The question is whether you will choose to elevate it.",
    summary_good: "Swift. Efficient. There is something admirable in a fast page — it respects the visitor's time, which is the only currency that truly matters."
  },

  mrbeast: {
    name: "MrBeast",
    icon: "\u{1F4B0}",
    roasts: {
      slow_ttfb: "TTFB is {ttfb}ms! BRO. Your server is SLEEPING! That's like buffering at the START of a video. People are GONE before it even loads!",
      medium_ttfb: "{ttfb}ms TTFB. Not great. Every millisecond you waste is a viewer — I mean visitor — you LOSE!",
      fast_ttfb: "{ttfb}ms! FAST! Your server is CRACKED. That's what I like to see!",
      slow_total: "{totalTime} SECONDS?! Do you know how many people you just LOST?! At 3 seconds you lose 53% of mobile visitors. This is a MASSACRE!",
      medium_total: "{totalTime}s. MID. Not fast enough. Would YOU wait {totalTime} seconds for a YouTube video to start? NO YOU WOULDN'T!",
      fast_total: "{totalTime}s! SPEED! Retention = MONEY. You're doing it RIGHT!",
      huge_html: "{size}KB?! Your page is MASSIVE and not in a good way! That's like uploading a 4K video when 1080p looks the SAME!",
      large_html: "{size}KB. CHUNKY. Trim it. Compress it. Speed is EVERYTHING in the attention economy!",
      no_compression: "NO COMPRESSION?! You're sending FAT pages when you could compress them 70%! That's like leaving FREE MONEY on the table! FREE!",
      has_compression: "Compression ON. Good. That's free performance. I LOVE free performance!",
      no_cache: "No caching! Every single visit downloads EVERYTHING! That's like re-uploading a video every time someone watches it! INSANE!",
      extreme_scripts: "{scripts} SCRIPTS! Your page is LAGGING! Every script is a frame drop. Nobody watches a laggy video. Nobody visits a laggy site!",
      many_scripts: "{scripts} scripts! That's TOO MANY! Audit them! I bet half of them do NOTHING!",
      many_third_party: "{thirdParty} THIRD-PARTY scripts! That's {thirdParty} companies SLOWING YOU DOWN! You're paying for THEIR bloat with YOUR speed!",
      some_third_party: "{thirdParty} external scripts. Each one is a RISK to your load time. Monitor them CLOSELY!",
      many_stylesheets: "{stylesheets} CSS files! EACH ONE blocks rendering! Your visitors see a BLANK PAGE while {stylesheets} files load! COMBINE THEM!",
      some_stylesheets: "{stylesheets} stylesheets. Could be fewer. Fewer = FASTER!",
      many_redirects: "{redirects} REDIRECTS! Your URL bounces {redirects} times before anyone sees ANYTHING! Each bounce = lost milliseconds = lost PEOPLE!",
      has_redirect: "A redirect. That's added latency. Make sure it's WORTH IT!",
      no_hints: "No preload, no preconnect, NO NOTHING! You're not giving the browser ANY head start! That's LEAVING SPEED ON THE TABLE!",
      has_preload: "Preloading resources! SMART! Giving the browser a HEAD START!",
      many_inline: "{inline} inline scripts! Can't cache them! Every visit re-downloads ALL of that! Extract them! SAVE BANDWIDTH!",
    },
    summary_bad: "DISASTER! Your page is SLOWER than a dial-up connection! But here's the thing — the fixes are EASY. Ten minutes of work could 10x your speed. DO IT!",
    summary_ok: "MID. You're at like 60%. I didn't build a $1B brand with MID speed. Level up! COMPRESS! CACHE! OPTIMIZE!",
    summary_good: "THIS IS CRACKED! Fast page, fast server, happy visitors! You're in the top 20%. Now PUSH for top 5%! LET'S GO!"
  },

  billieeilish: {
    name: "Billie Eilish",
    icon: "\u{1F5A4}",
    roasts: {
      slow_ttfb: "{ttfb}ms. your server just... sits there. thinking about it. while everyone waits. that's not a vibe.",
      medium_ttfb: "{ttfb}ms. not terrible. not great either. just... there.",
      fast_ttfb: "{ttfb}ms. fast. clean. good.",
      slow_total: "{totalTime} seconds. that's forever. people leave. they always leave when you make them wait too long.",
      medium_total: "{totalTime}s. it's fine. fine is just... fine.",
      fast_total: "{totalTime}s. quick. i like that.",
      huge_html: "{size}KB. that's a lot. too much. let go of what you don't need.",
      large_html: "{size}KB. heavy. lighter is usually better. for pages. and for life maybe.",
      no_compression: "no compression. you're sending everything raw. unfiltered. that's not authentic. that's just wasteful.",
      has_compression: "compressed. clean.",
      no_cache: "no caching. every visit starts over. like you can't remember anything. that's not mysterious. that's just bad.",
      extreme_scripts: "{scripts} scripts. that's so heavy. strip it down. the best things are the simplest things.",
      many_scripts: "{scripts} scripts. too many voices. pick the ones that matter.",
      many_third_party: "{thirdParty} scripts from other people's servers. that's a lot of trust. maybe too much.",
      some_third_party: "{thirdParty} external scripts. just... be careful who you let in.",
      many_stylesheets: "{stylesheets} CSS files. each one makes people wait to see anything. that's not cool.",
      some_stylesheets: "{stylesheets} stylesheets. could be simpler.",
      many_redirects: "{redirects} redirects. your url doesn't know where it's going. relatable. but not good.",
      has_redirect: "a redirect. one is ok. more than one is a problem.",
      no_hints: "no preload. no preconnect. you're not helping the browser at all. it's trying. meet it halfway.",
      has_preload: "preloading. that's thoughtful. i appreciate that.",
      many_inline: "{inline} inline scripts. tangled up in the html. can't cache them. can't separate them. it's messy.",
    },
    summary_bad: "it's slow. really slow. but the thing about slow is you can fix it. one thing at a time. start now.",
    summary_ok: "it's ok. ok is not enough though. you know that.",
    summary_good: "fast. clean. honest. don't overthink it. just keep it going."
  },

  tolkien: {
    name: "J.R.R. Tolkien",
    icon: "\u{1F9D9}",
    roasts: {
      slow_ttfb: "{ttfb}ms — the server deliberates as long as the Council of Elrond before sending a single byte. Many visitors shall turn back before the gate opens.",
      medium_ttfb: "{ttfb}ms — not swift, not glacial. Like the march of the Ents — purposeful, but perhaps too measured for the urgency at hand.",
      fast_ttfb: "{ttfb}ms — swift as an arrow of the Galadhrim. The server answers the call without hesitation.",
      slow_total: "{totalTime} seconds — an age in the reckoning of the web. Many quests have been abandoned for less.",
      medium_total: "{totalTime}s — the journey is not unbearable, but a lighter pack would speed the way.",
      fast_total: "{totalTime}s. Swift passage. The browser arrives at its destination like an eagle of Manwe.",
      huge_html: "{size}KB — the HTML sprawls like Moria. Vast, but much of it may be empty halls and forgotten passages.",
      large_html: "{size}KB. A heavy tome. Not all pages need be as long as the Silmarillion.",
      no_compression: "The response travels uncompressed — each byte carried as a separate stone. Compress them, and the burden is halved.",
      has_compression: "The response is compressed. Wise — even the mightiest army travels light when speed is needed.",
      no_cache: "No caching enchantments protect this site. Each visit requires the full journey anew, as if the paths of memory were unmade each night.",
      extreme_scripts: "{scripts} scripts weigh upon this page like the burden of the One Ring. Each one adds to the heaviness of the load.",
      many_scripts: "{scripts} scripts march upon this page like an army. Not all are needed for the battle ahead.",
      many_third_party: "{thirdParty} scripts summoned from distant realms. Each one brings power — and risk. Not all allies can be trusted.",
      some_third_party: "{thirdParty} external scripts. Choose your allies carefully.",
      many_stylesheets: "{stylesheets} stylesheets guard the gates of rendering. The visitor sees nothing until all {stylesheets} have been consulted. A long council indeed.",
      some_stylesheets: "{stylesheets} CSS files. The visual design requires deliberation, but less would speed the rendering.",
      many_redirects: "{redirects} redirects — the URL wanders like Frodo through the Dead Marshes, each wrong turn adding peril and delay.",
      has_redirect: "A redirect. A detour on the road. May it be the only one.",
      no_hints: "No resource hints illuminate the path ahead. Even the wisest browser benefits from foreknowledge of what lies beyond the next request.",
      has_preload: "Resource hints chart the path ahead. The browser moves with purpose, like a ranger who knows the trail.",
      many_inline: "{inline} inline scripts embedded within the HTML like dwarven runes carved into the living stone — permanent, uncacheable, heavy.",
    },
    summary_bad: "The darkness is deep here. The page labors under a great burden. But even in the darkest performance audit, there is hope. Begin with compression.",
    summary_ok: "The foundation holds, but the fortress is heavy with unnecessary weight. Lighten the load and the journey becomes swifter.",
    summary_good: "A swift and worthy page. The walls are strong, the response times short. A domain built to endure."
  },

  bezos: {
    name: "Jeff Bezos",
    icon: "\u{1F4E6}",
    roasts: {
      slow_ttfb: "TTFB is {ttfb}ms. Every 100ms of latency costs 1% in sales. At {ttfb}ms, do the math. It's not good.",
      medium_ttfb: "{ttfb}ms. There's a measurable business impact here. Server response time is a direct input to conversion.",
      fast_ttfb: "{ttfb}ms. Good operational metric. This is table stakes — maintain it.",
      slow_total: "{totalTime}s total load. At Amazon we proved that every 100ms of latency costs revenue. At {totalTime}s, you're hemorrhaging conversions.",
      medium_total: "{totalTime}s. Suboptimal. There's waste in the pipeline. Find it. Remove it. Measure the improvement.",
      fast_total: "{totalTime}s. Efficient delivery. Good operational metric.",
      huge_html: "{size}KB. There's significant waste in the system. This is a direct P&L impact — bandwidth costs, user abandonment, SEO penalties. All measurable.",
      large_html: "{size}KB. Moderate bloat. Apply the two-pizza team rule: if the HTML needs more than two engineers to review, it's too big.",
      no_compression: "No compression. You're paying for bandwidth you don't need to use. That's a direct cost center with a simple fix. Enable gzip. Today.",
      has_compression: "Compression enabled. Basic operational hygiene confirmed.",
      no_cache: "No Cache-Control. Every returning customer downloads the full payload. At scale, that's a systemic inefficiency that compounds daily.",
      extreme_scripts: "{scripts} scripts. Each one adds latency. Latency kills conversion. This is a direct P&L impact. Audit every single one.",
      many_scripts: "{scripts} scripts. Apply the working-backwards framework: which of these does the customer actually need?",
      many_third_party: "{thirdParty} third-party scripts. That's {thirdParty} external dependencies on your critical path. Each one is a single point of failure for your performance SLA.",
      some_third_party: "{thirdParty} external scripts. Monitor them. They're outside your operational control.",
      many_stylesheets: "{stylesheets} render-blocking CSS files. The customer sees nothing until all {stylesheets} are loaded. That's a Day 2 experience.",
      some_stylesheets: "{stylesheets} CSS files. Minor consolidation opportunity.",
      many_redirects: "{redirects} redirects. Each one is a full round-trip. At scale, that's measurable wasted latency across your entire customer base.",
      has_redirect: "One redirect. Acceptable if it's resolving to the canonical URL. Otherwise, eliminate it.",
      no_hints: "No resource hints. Preconnect and preload are free optimizations. Leaving them unused is leaving customer experience on the table.",
      has_preload: "Resource hints deployed. You're optimizing the critical path. Good operational thinking.",
      many_inline: "{inline} inline scripts. These can't be cached. At scale, that's repeated bandwidth cost for every page view. Extract and serve externally.",
    },
    summary_bad: "The performance metrics tell a clear story: this is a Day 2 website. Customer experience has been deprioritized. Work backwards from what the customer needs: speed.",
    summary_ok: "Fundamentals are in place but the details are sloppy. At scale, sloppy performance becomes systemic failure. Tighten up.",
    summary_good: "Good operational health. The performance flywheel is spinning. Keep investing in speed — it compounds."
  },

  tarantino: {
    name: "Quentin Tarantino",
    icon: "\u{1F3AC}",
    roasts: {
      slow_ttfb: "{ttfb}ms TTFB! Your server is sitting there, doing NOTHING, while the audience walks out! That's like a movie with 30 minutes of black screen before the first shot!",
      medium_ttfb: "{ttfb}ms. Look, it's not unwatchable. But it's not SNAPPY. I want SNAPPY dialogue AND snappy server responses.",
      fast_ttfb: "{ttfb}ms. BANG. Server responds like a gunshot. I respect that.",
      slow_total: "{totalTime} seconds to load. You know what happens in {totalTime} seconds? The audience walks out. YOUR COMPETITOR'S theater. That's where they go.",
      medium_total: "{totalTime}s. It's like a slow-burn opening — some people dig it, most don't. Speed it up.",
      fast_total: "{totalTime}s. Snappy. Like good dialogue. Perfect pacing.",
      huge_html: "{size}KB! What is this, the director's cut of HTML?! Nobody asked for this! TRIM. IT. DOWN.",
      large_html: "{size}KB. Bloated. Like a director's cut nobody asked for.",
      no_compression: "No compression?! You're serving raw, uncompressed bytes like a film with no editing! Edit your responses! Cut the fat!",
      has_compression: "Compressed. Good editing. The final cut is always leaner.",
      no_cache: "No caching! That's like making the audience buy tickets AGAIN for the same movie! Cache the assets!",
      extreme_scripts: "{scripts} scripts! This is the final act of a Michael Bay movie! Too much! Way too much! EXPLOSIONS everywhere but no SUBSTANCE!",
      many_scripts: "{scripts} scripts. You need a script EDITOR, not more scripts. Ba dum tss.",
      many_third_party: "{thirdParty} third-party scripts! That's {thirdParty} actors you didn't audition! And they're RUINING the scene!",
      some_third_party: "{thirdParty} external scripts. Make sure they're pulling their weight.",
      many_stylesheets: "{stylesheets} CSS files blocking the first paint! Your visitors are staring at a blank screen! That's NOT an artistic choice!",
      some_stylesheets: "{stylesheets} stylesheets. The costume department is getting out of hand.",
      many_redirects: "{redirects} redirects. The URL takes MORE detours than Pulp Fiction's timeline. And at least MINE was intentional!",
      has_redirect: "A redirect. Fine. One plot twist. But keep it to one.",
      no_hints: "No resource hints. You're not setting up the next scene AT ALL. Foreshadowing isn't just for movies — it's for BROWSERS.",
      has_preload: "Preloading! Setting up the next scene while the current one plays! THAT'S filmmaking. I mean, web development.",
      many_inline: "{inline} inline scripts scattered through the HTML like improvised dialogue. Sometimes it works. Usually it doesn't.",
    },
    summary_bad: "Your page's performance is a BLOODBATH. And not the cool Tarantino kind. The boring kind where nothing loads and nobody's watching.",
    summary_ok: "Decent pacing. Like a good B-movie. Watchable. But you want a MASTERPIECE? Cut harder.",
    summary_good: "SNAPPY. Like the opening of Kill Bill. Clean, fast, instant impact. THAT'S how you do it."
  },

  nolan: {
    name: "Christopher Nolan",
    icon: "\u{1F3A5}",
    roasts: {
      slow_ttfb: "{ttfb}ms. Time is the fundamental constraint here. Your server is operating on a different temporal plane than your users.",
      medium_ttfb: "{ttfb}ms. The response time exists in a liminal space — not slow enough to notice, not fast enough to impress.",
      fast_ttfb: "{ttfb}ms. Precise. The audience doesn't notice the craft — that's when you know it's working.",
      slow_total: "{totalTime}s. In those {totalTime} seconds, the user experiences a micro-lifetime of anticipation, doubt, and ultimately, departure. Time dilation, but not the useful kind.",
      medium_total: "{totalTime}s. The pacing is off. Every frame — every millisecond — should serve the experience.",
      fast_total: "{totalTime}s. Clean execution. When done right, speed is invisible.",
      huge_html: "{size}KB. The payload is dense with information, but density without purpose is complexity. Complexity is the enemy of execution.",
      large_html: "{size}KB. Question every element — does it serve the central experience?",
      no_compression: "No compression. You're transmitting the unedited footage. The audience doesn't need the raw takes — they need the final cut.",
      has_compression: "Compressed. The essence preserved, the excess removed. Good craft.",
      no_cache: "No cache headers. The browser has no temporal memory — each visit begins from zero. In a story about time, this is the wrong kind of reset.",
      extreme_scripts: "{scripts} scripts. Complexity without purpose is the enemy of performance. Audit each one — does it serve the narrative?",
      many_scripts: "{scripts} scripts. The page is overproduced. Sometimes the most powerful scenes have the least happening.",
      many_third_party: "{thirdParty} external scripts. That's {thirdParty} elements outside your directorial control. In filmmaking, control is everything.",
      some_third_party: "{thirdParty} third-party dependencies. Each one introduces variables you can't predict.",
      many_stylesheets: "{stylesheets} CSS files. Each one is a gate the browser must pass through before painting. The audience sees nothing during this preamble.",
      some_stylesheets: "{stylesheets} stylesheets. The visual layer requires fewer blocking resources.",
      many_redirects: "{redirects} redirects. The timeline folds {redirects} times before reaching the destination. Unlike Inception, these layers add nothing.",
      has_redirect: "A redirect. A narrative detour. Acceptable if it serves the final destination.",
      no_hints: "No resource hints. The browser enters each scene unprepared. Foreshadowing isn't just a storytelling device — it's a performance technique.",
      has_preload: "Resource hints deployed. The browser knows what's coming next. Preparation enables precision.",
      many_inline: "{inline} inline scripts. Embedded in the structure. Inseparable from the page. That limits your ability to optimize each component independently.",
    },
    summary_bad: "The performance structure has collapsed. Rebuild from the core principle: the user's time is the most valuable resource. Every millisecond must earn its place.",
    summary_ok: "The framework holds, but the execution has temporal gaps. Close them systematically. Precision in timing is everything.",
    summary_good: "Precisely executed. The performance is invisible — the user experiences only the content. That's mastery."
  },

  ryanreynolds: {
    name: "Ryan Reynolds",
    icon: "\u{1F609}",
    roasts: {
      slow_ttfb: "{ttfb}ms TTFB. Your server is taking longer to respond than I take to pick a movie. And I'm VERY indecisive.",
      medium_ttfb: "{ttfb}ms. Not great. Not terrible. Like my Rotten Tomatoes average. Before Deadpool, obviously.",
      fast_ttfb: "{ttfb}ms. Quick! Faster than I can come up with a self-deprecating joke. Almost.",
      slow_total: "{totalTime}s to load. I've had faster conversations with my kids. And they're three.",
      medium_total: "{totalTime}s. It's like waiting for my Aviation Gin to pour. Acceptable, but I know it could be faster.",
      fast_total: "{totalTime}s — quick and clean. Like a perfect comedic beat.",
      huge_html: "{size}KB. That's... chunky. Like me after the holidays. Trim it down.",
      large_html: "{size}KB. There's definitely some stuff in there that doesn't need to be. Like my scenes in Green Lantern.",
      no_compression: "No compression. You're sending the full, uncompressed page. That's like sending every outtake along with the final movie. Nobody wants that. Trust me.",
      has_compression: "Compressed! Great. Less bytes, more speed. If only I could compress my insecurities that easily.",
      no_cache: "No caching. So every time someone visits, they download EVERYTHING again. That's like re-watching Green Lantern voluntarily. Why would you do that?",
      extreme_scripts: "{scripts} scripts! Your page has more scripts than I have failed auditions. And that's saying something.",
      many_scripts: "{scripts} scripts. Each one doing... something. Probably. Maybe audit them.",
      many_third_party: "{thirdParty} third-party scripts. That's {thirdParty} uninvited guests at your performance party. And they're drinking all the bandwidth.",
      some_third_party: "{thirdParty} external scripts. They're like that friend who says they'll be quick but never is.",
      many_stylesheets: "{stylesheets} CSS files! Each one blocks rendering! Your visitors are staring at nothing while {stylesheets} style decisions load. Pick one look and commit!",
      some_stylesheets: "{stylesheets} stylesheets. A few more wardrobe changes than necessary.",
      many_redirects: "{redirects} redirects. Your URL has commitment issues. 'Maybe THIS is where I live? No wait, THERE.' Pick a URL. Commit.",
      has_redirect: "A redirect. OK. One detour. Like the scenic route but for URLs.",
      no_hints: "No preload or preconnect. The browser has NO idea what's coming. It's like watching a movie without trailers. Actually, that sounds nice. But for performance, it's bad.",
      has_preload: "Preloading resources! Smart! Like reading the script before showing up on set. I should try that sometime.",
      many_inline: "{inline} inline scripts. That's {inline} pieces of code that can't be cached. Like my improv — fresh every time, but not always efficient.",
    },
    summary_bad: "Your page is slower than my career before Deadpool. And that was PAINFUL. But hey — turnarounds happen. Start compressing.",
    summary_ok: "Solid C+. In school that means 'needs improvement.' In performance terms it means 'your users are slightly annoyed.' Fix it.",
    summary_good: "Genuinely fast. I'm not being sarcastic for once. This is what a well-optimized page looks like."
  },

  keanureeves: {
    name: "Keanu Reeves",
    icon: "\u{1F9D8}",
    roasts: {
      slow_ttfb: "{ttfb}ms. That's... yeah, the server's taking a while. People are patient, but not that patient.",
      medium_ttfb: "{ttfb}ms. It's OK. Could be better. You know?",
      fast_ttfb: "{ttfb}ms. That's nice. Quick and clean.",
      slow_total: "{totalTime} seconds. That's a long time to wait. Even I'd probably click away. And I'm pretty patient.",
      medium_total: "{totalTime}s. Not bad. Not amazing. There's room to do better. Gently.",
      fast_total: "{totalTime}s. Fast. Respectful of people's time. That matters.",
      huge_html: "{size}KB. That's heavy. Lighter things move easier. For pages. And maybe for everything.",
      large_html: "{size}KB. A bit much. Simplifying usually helps.",
      no_compression: "No compression. Sending everything as-is. A little compression goes a long way. It's worth doing.",
      has_compression: "Compressed. Thoughtful.",
      no_cache: "No caching. Every visit starts fresh. That's not always bad, but... it's usually better to remember.",
      extreme_scripts: "{scripts} scripts. That's a lot. Simplifying things usually makes them better.",
      many_scripts: "{scripts} scripts. Worth looking at which ones really need to be there.",
      many_third_party: "{thirdParty} scripts from other places. That's a lot of trust. Just... be mindful.",
      some_third_party: "{thirdParty} external scripts. Keep an eye on them.",
      many_stylesheets: "{stylesheets} CSS files. That's a lot of things blocking the page from showing up. People deserve to see something quickly.",
      some_stylesheets: "{stylesheets} stylesheets. Could be simpler.",
      many_redirects: "{redirects} redirects. The URL is wandering. Help it find home.",
      has_redirect: "A redirect. Sometimes you need to go somewhere else first. That's OK.",
      no_hints: "No resource hints. The browser doesn't know what's coming. A little heads-up would be kind.",
      has_preload: "Preloading. That's considerate. The browser appreciates it.",
      many_inline: "{inline} inline scripts. They're stuck in the page. It'd be nicer if they could live on their own.",
    },
    summary_bad: "It's not great right now. But that's OK. Everything worth building takes time. Start with compression and caching. Be kind to the process.",
    summary_ok: "It's in a decent place. Not perfect, but nothing is. Keep working on it. Gently.",
    summary_good: "This is good work. Honest, solid work. Be proud of it."
  },

  orwell: {
    name: "George Orwell",
    icon: "\u{1F4DD}",
    roasts: {
      slow_ttfb: "{ttfb}ms. The server withholds its response like a bureaucracy processing a simple request. The citizen waits.",
      medium_ttfb: "{ttfb}ms. Adequate. But 'adequate' in performance, as in politics, is a word used to avoid criticism.",
      fast_ttfb: "{ttfb}ms. Prompt. The server does its job without ceremony. As it should.",
      slow_total: "{totalTime}s. The reader's time is not yours to waste. This is a plain fact.",
      medium_total: "{totalTime}s. Passable. But passable is another word for forgettable.",
      fast_total: "{totalTime}s. Speed is a form of respect for the reader.",
      huge_html: "{size}KB. Good prose is lean. Good HTML should be too.",
      large_html: "{size}KB. More than necessary. Trim what doesn't serve clarity.",
      no_compression: "No compression. The bytes travel uncompressed — wasteful in the way that all unexamined processes are wasteful.",
      has_compression: "Compressed. Efficient. Nothing wasted.",
      no_cache: "No caching. The browser is forced to forget and re-learn everything. Deliberate amnesia is a tool of control, not of performance.",
      extreme_scripts: "{scripts} scripts. Each one is a small tax on the reader's patience. The total is not small.",
      many_scripts: "{scripts} scripts. Not all of them serve the reader. Find the ones that don't and remove them.",
      many_third_party: "{thirdParty} external scripts. {thirdParty} entities you've allowed to influence your page speed. Surveillance capitalism has entered your performance budget.",
      some_third_party: "{thirdParty} scripts from outside. Each one watches your users while slowing them down.",
      many_stylesheets: "{stylesheets} render-blocking CSS files. The visitor sees nothing while the page decides how to present itself. The message is delayed by the medium.",
      some_stylesheets: "{stylesheets} stylesheets. Consolidation would reduce the delay between request and visible content.",
      many_redirects: "{redirects} redirects. The URL is rerouted {redirects} times. Bureaucratic routing applied to web requests.",
      has_redirect: "A redirect. One layer of indirection. Tolerable, but question its necessity.",
      no_hints: "No resource hints. The browser receives no advance information about critical resources. Plain information, plainly communicated, is always better.",
      has_preload: "Resource hints provided. Clear, direct communication with the browser. Good practice.",
      many_inline: "{inline} inline scripts. Embedded, inseparable from the document. The code cannot be independently cached or audited.",
    },
    summary_bad: "The performance is poor. This is not a matter of opinion. The numbers are clear and the fixes are straightforward.",
    summary_ok: "Passable. But in a competitive landscape, passable performance is another word for losing. Slowly.",
    summary_good: "Clean, fast, efficient. No unnecessary overhead. This is how web pages should be built."
  },

  nabokov: {
    name: "Vladimir Nabokov",
    icon: "\u{2728}",
    roasts: {
      slow_ttfb: "{ttfb}ms — the server responds with the deliberation of a novelist choosing the opening word. Alas, web users lack the patience of literary critics.",
      medium_ttfb: "{ttfb}ms. Neither brisk nor unconscionable. The server exists in that twilight zone between efficiency and indolence.",
      fast_ttfb: "{ttfb}ms — brisk, efficient, almost elegant in its promptness.",
      slow_total: "{totalTime}s — an unconscionable delay. The modern web user has the patience of a hummingbird and you are asking them to meditate.",
      medium_total: "{totalTime}s. One waits. Not uncomfortably, but with a faint awareness that things could be swifter.",
      fast_total: "{totalTime}s. Swift. The page materializes before the eye can register its absence.",
      huge_html: "{size}KB — the HTML is corpulent. There is, one suspects, considerable bloat hiding beneath the surface like unedited passages in a first draft.",
      large_html: "{size}KB. A substantial page. Some editing is advisable.",
      no_compression: "The response arrives uncompressed — every byte transmitted in its original, unrefined state. Like publishing a first draft without revision.",
      has_compression: "Compressed. The response arrives distilled to its essence. Elegant.",
      no_cache: "No caching mechanism. The browser, that faithful reader, is asked to rediscover the page from scratch with each visit. Inefficient in the extreme.",
      extreme_scripts: "{scripts} scripts clutter this page like footnotes in an academic paper nobody asked for.",
      many_scripts: "{scripts} scripts. A collection that would benefit from aggressive curation.",
      many_third_party: "{thirdParty} scripts from external sources, each one a small intrusion of foreign code into your carefully constructed page. Compositional impurity.",
      some_third_party: "{thirdParty} external dependencies. Each one an invited guest who may overstay their welcome.",
      many_stylesheets: "{stylesheets} CSS files, each one delaying the moment the page reveals itself — like {stylesheets} curtain calls before the performance begins.",
      some_stylesheets: "{stylesheets} stylesheets. The visual composition requires fewer intermediaries.",
      many_redirects: "{redirects} redirects. The URL performs an elaborate dance of indirection before arriving at its destination. Unnecessarily theatrical.",
      has_redirect: "A redirect. A small detour. Forgivable if purposeful.",
      no_hints: "No resource hints. The browser enters unprepared, like a reader opening a novel without a dust jacket — possible, but less than ideal.",
      has_preload: "Resource hints deployed with precision. The browser knows what to expect. Preparation elevates execution.",
      many_inline: "{inline} inline scripts woven into the HTML like digressions in a sentence — individually forgivable, collectively exhausting.",
    },
    summary_bad: "A performance disaster with a certain dark charm. The fixes are prosaic — compression, caching, consolidation. The challenge is caring enough to apply them.",
    summary_ok: "Middling. The page neither offends nor impresses. It exists in that gray territory between neglect and optimization.",
    summary_good: "Admirably swift. A few refinements and it would approach something genuinely well-crafted."
  },

  bulgakov: {
    name: "Mikhail Bulgakov",
    icon: "\u{1F608}",
    roasts: {
      slow_ttfb: "{ttfb}ms! The server responds with the enthusiasm of a Soviet bureaucrat at 4:59 PM. 'Your page? Yes, comrade, it will be ready. Eventually.'",
      medium_ttfb: "{ttfb}ms. Not terrible by Moscow standards. But the internet is not Moscow. Not yet, anyway.",
      fast_ttfb: "{ttfb}ms — quick! Like the devil passing through. Effective.",
      slow_total: "{totalTime}s. The queue to view your website is shorter than a bread line, but feels equally interminable.",
      medium_total: "{totalTime}s. The page arrives with the punctuality of a Moscow bus — technically on schedule, subjectively late.",
      fast_total: "{totalTime}s. Fast. One almost suspects dark magic was involved.",
      huge_html: "{size}KB. Bloated. Like a novel that the censors kept adding to instead of cutting.",
      large_html: "{size}KB. A substantial document. The committee has been adding to it, clearly.",
      no_compression: "No compression. The bytes travel uncompressed, bloated, like a Soviet report filled with unnecessary paragraphs praising the system.",
      has_compression: "Compressed. Someone defied the committee and actually optimized something. Remarkable.",
      no_cache: "No caching. The browser forgets everything, like a citizen who saw something they shouldn't have. Every visit starts from zero.",
      extreme_scripts: "{scripts} scripts! The page groans under their weight like a communal apartment groans under the weight of its residents.",
      many_scripts: "{scripts} scripts. A collective of code, each module convinced of its own importance.",
      many_third_party: "{thirdParty} scripts from external servers. {thirdParty} foreign delegations, each one consuming resources meant for your citizens — I mean, users.",
      some_third_party: "{thirdParty} external scripts. Foreign assistance is not always assistance.",
      many_stylesheets: "{stylesheets} CSS files blocking the page. The visitor sees nothing — a blank screen — while {stylesheets} aesthetic committees deliberate.",
      some_stylesheets: "{stylesheets} stylesheets. The design bureau could consolidate.",
      many_redirects: "{redirects} redirects. The URL is passed between departments like a requisition form that nobody wants to approve.",
      has_redirect: "A redirect. The URL is sent to another office. One hopes it's the right one this time.",
      no_hints: "No resource hints. The browser arrives uninformed, like a new transfer to a ministry where nobody explains anything.",
      has_preload: "Resource hints! Someone wrote a helpful memo. In this system, that's practically a miracle.",
      many_inline: "{inline} inline scripts. Embedded directly in the HTML. Irremovable. Like a party member assigned to your apartment.",
    },
    summary_bad: "A magnificent catastrophe. The performance is as bad as the plumbing in a communal apartment. But here we are, and here is the fix list.",
    summary_ok: "Not terrible. Not good. The page occupies that uniquely Russian middle ground between 'it could be worse' and 'it should be better.'",
    summary_good: "Surprisingly fast. One suspects dark magic — or, more likely, competent engineering. Both are equally rare."
  },

  bradbury: {
    name: "Ray Bradbury",
    icon: "\u{1F525}",
    roasts: {
      slow_ttfb: "{ttfb}ms. The server takes its time, like a letter traveling through the mail of a world that's forgotten how to hurry. But the web remembers.",
      medium_ttfb: "{ttfb}ms. Not instant, but not eternity. A pause between heartbeats.",
      fast_ttfb: "{ttfb}ms — quick, like the first warm day of spring. You barely notice it happening.",
      slow_total: "{totalTime}s. In that time, the visitor has already imagined leaving, and then left. The future moves fast.",
      medium_total: "{totalTime}s. The page arrives like a memory — not instantly, but before you've fully noticed the waiting.",
      fast_total: "{totalTime}s. Immediate. Like opening a book and falling straight into the story.",
      huge_html: "{size}KB. Dense with the accumulated weight of... well, something. Whether it's useful is another question entirely.",
      large_html: "{size}KB. A heavy page. Not all weight is substance.",
      no_compression: "Uncompressed. The page travels in its full, raw form — every byte a small ember, every kilobyte a small fire of wasted bandwidth.",
      has_compression: "Compressed. The essence transmitted, the excess burned away.",
      no_cache: "No caching. The page vanishes from memory after each visit, like a dandelion seed blown away. The browser starts from nothing each time.",
      extreme_scripts: "{scripts} scripts. The page carries them like old photographs — some treasured, most forgotten, all slowing the journey.",
      many_scripts: "{scripts} scripts. A collection. Some illuminate, some merely weigh.",
      many_third_party: "{thirdParty} scripts from distant servers, each one a small voice from somewhere else, talking over your page.",
      some_third_party: "{thirdParty} external scripts. Voices from elsewhere. Make sure they're saying something worth hearing.",
      many_stylesheets: "{stylesheets} CSS files. The page hides behind them like a story behind an overly ornate cover. Let the content show sooner.",
      some_stylesheets: "{stylesheets} stylesheets. A gentle delay before the page reveals itself.",
      many_redirects: "{redirects} redirects. The URL drifts between destinations like a paper airplane caught in changing winds.",
      has_redirect: "A redirect. A brief detour on the way to something.",
      no_hints: "No resource hints. The browser enters each moment blind, unprepared for what comes next.",
      has_preload: "Preloading. The browser sees what's coming. There's something hopeful about that.",
      many_inline: "{inline} inline scripts, woven into the page like thread into fabric — inseparable, permanent.",
    },
    summary_bad: "The page is slow. Like a clock that runs behind. But every slow clock can be fixed. Start with the simplest repair.",
    summary_ok: "Halfway between fast and slow. The bones are good. Now give it speed — give it life.",
    summary_good: "Fast and bright and alive. Like a page that wants to be read. Don't let it grow old without tending it."
  },

  christie: {
    name: "Agatha Christie",
    icon: "\u{1F50D}",
    roasts: {
      slow_ttfb: "{ttfb}ms. The server's response time is suspicious. In my experience, delays of this magnitude suggest either neglect or an infrastructure that isn't fit for purpose.",
      medium_ttfb: "{ttfb}ms. Adequate, but not above suspicion. I'd investigate the server configuration.",
      fast_ttfb: "{ttfb}ms. Prompt. Efficient. One appreciates a system that doesn't waste time.",
      slow_total: "{totalTime}s. The visitor will lose patience. Patience is a virtue, but it is not a web browsing strategy.",
      medium_total: "{totalTime}s. Tolerable. But the best pages, like the best mysteries, don't make you wait unnecessarily.",
      fast_total: "{totalTime}s. Swift and efficient. The case resolves quickly.",
      huge_html: "{size}KB. That's quite substantial. Somewhere in that bulk, I suspect there is unnecessary code hiding.",
      large_html: "{size}KB. More than expected. The evidence suggests bloat.",
      no_compression: "No compression. The response is transmitted in its entirety, uncompressed. A peculiar choice — like sending an entire manuscript when a summary would suffice.",
      has_compression: "Compressed. Efficient communication. No wasted effort.",
      no_cache: "No caching. The browser retains nothing between visits. Most peculiar — it's as if someone deliberately erased the evidence each time.",
      extreme_scripts: "{scripts} scripts. Each one must be investigated for its impact. I suspect several are guilty of significant performance crimes.",
      many_scripts: "{scripts} scripts. Too many suspects. Time to narrow the field.",
      many_third_party: "{thirdParty} scripts from external sources. {thirdParty} unknown parties with access to your page. In a mystery, that many suspects means trouble.",
      some_third_party: "{thirdParty} external scripts. Each one a person of interest in this performance investigation.",
      many_stylesheets: "{stylesheets} render-blocking CSS files. The page reveals nothing while {stylesheets} files are examined. A very slow reveal, even by my standards.",
      some_stylesheets: "{stylesheets} stylesheets. A modest delay. Not the primary suspect, but worth noting.",
      many_redirects: "{redirects} redirects. The URL leads one on a chase through {redirects} false addresses. Terribly inefficient detective work.",
      has_redirect: "One redirect. A misdirection. Acceptable if it leads to the truth.",
      no_hints: "No resource hints. The browser proceeds without clues. Even Poirot benefits from advance information.",
      has_preload: "Resource hints provided. Good — the browser has the clues it needs to act decisively.",
      many_inline: "{inline} inline scripts embedded in the scene. They can't be extracted for independent analysis. Contaminated evidence.",
    },
    summary_bad: "The evidence is clear: this page's performance has been the victim of systematic neglect. The culprits — missing compression, absent caching, excess scripts — are not difficult to identify.",
    summary_ok: "A middling case. Some clues point to competence, others to carelessness. The truth lies in the details.",
    summary_good: "A well-ordered scene. The performance is clean, the response swift. I would, however, recommend periodic audits."
  },

  strugatsky: {
    name: "Strugatsky Brothers",
    icon: "\u{1FA90}",
    roasts: {
      slow_ttfb: "{ttfb}ms — the server processes the request with the urgency of an Institute committee reviewing a Zone artifact. The user waits in the queue.",
      medium_ttfb: "{ttfb}ms. Within operational parameters, but the parameters themselves are questionable.",
      fast_ttfb: "{ttfb}ms. The system responds within acceptable parameters. Efficient.",
      slow_total: "{totalTime}s. Time moves differently in the Zone, but on the internet, {totalTime} seconds is enough for the visitor to question whether the destination is worth reaching.",
      medium_total: "{totalTime}s. Functional. But 'functional' is a word used by people who have stopped optimizing.",
      fast_total: "{totalTime}s. Efficient. The best technology is the technology you don't notice.",
      huge_html: "{size}KB. A heavy payload for what should be a simple transmission. The signal-to-noise ratio is concerning.",
      large_html: "{size}KB. Heavy. The transmission could be optimized.",
      no_compression: "No compression. The data travels at full size, like a supply convoy that refused to consolidate its cargo. Logistically inexcusable.",
      has_compression: "Compressed. The transmission is optimized. Acceptable protocol.",
      no_cache: "No caching protocol. The system maintains no record of previous interactions. In the Institute, this would be considered a data retention failure.",
      extreme_scripts: "{scripts} scripts. The technological overhead is considerable. Not all of it is necessary. Probably.",
      many_scripts: "{scripts} scripts. Each one a module in an increasingly complex system. Complexity breeds anomalies.",
      many_third_party: "{thirdParty} scripts from external systems. {thirdParty} unknown variables in your operational equation. In the Zone, unknown variables are treated with extreme caution.",
      some_third_party: "{thirdParty} external dependencies. Monitor them. External systems are unpredictable.",
      many_stylesheets: "{stylesheets} rendering dependencies. The visual interface is blocked by {stylesheets} sequential processes. Serial execution where parallel would suffice.",
      some_stylesheets: "{stylesheets} CSS files. A minor bottleneck in the rendering pipeline.",
      many_redirects: "{redirects} redirects. The signal bounces {redirects} times. In communications theory, each relay degrades the signal.",
      has_redirect: "A redirect. One relay. Within acceptable parameters if necessary.",
      no_hints: "No resource hints. The browser operates without intelligence about upcoming resource requirements. Suboptimal tactical planning.",
      has_preload: "Resource hints deployed. The browser has advance intelligence. Good operational planning.",
      many_inline: "{inline} inline code modules. Embedded in the transmission. Cannot be cached independently. A design constraint with measurable cost.",
    },
    summary_bad: "The anomaly is severe. Performance exists in a state that defies acceptable operational parameters. Begin with compression. Document everything.",
    summary_ok: "Within expected parameters. But expected parameters are not aspirational. Push further.",
    summary_good: "A well-constructed system operating at speed. The Strugatsky brothers would note: even well-constructed systems require maintenance."
  },

  jobs: {
    name: "Steve Jobs",
    icon: "\u{1F34E}",
    roasts: {
      slow_ttfb: "{ttfb}ms. Your server responds slower than a Dell. That's not OK. Speed is a feature. The MOST important feature.",
      medium_ttfb: "{ttfb}ms. Not bad. Not great. At Apple, 'not bad' gets you fired.",
      fast_ttfb: "{ttfb}ms. That's the kind of attention to performance detail I respect.",
      slow_total: "{totalTime}s. People don't wait. They shouldn't have to. You know what loads instantly? A great product.",
      medium_total: "{totalTime}s. Close. But close only counts in horseshoes. Ship something faster.",
      fast_total: "{totalTime}s. Clean. Instant. Like an iPhone waking from sleep. That's the standard.",
      huge_html: "{size}KB. Strip away everything that isn't essential. Then strip away more.",
      large_html: "{size}KB. More than needed. Simplicity is the ultimate sophistication.",
      no_compression: "No compression. You're shipping unoptimized bytes. We spent months saving kilobytes on the original Mac. This is lazy.",
      has_compression: "Compressed. Good. The best engineering is the engineering you don't see.",
      no_cache: "No caching. Every visit reloads everything. That's not a design choice — that's a failure to think about the experience.",
      extreme_scripts: "{scripts} scripts. This page has more bloat than a feature list designed by engineers with no taste.",
      many_scripts: "{scripts} scripts. How many of those actually improve the user experience? I'd bet less than half.",
      many_third_party: "{thirdParty} external scripts. You've invited {thirdParty} other companies to slow down YOUR experience. That's not curating — that's capitulating.",
      some_third_party: "{thirdParty} third-party scripts. Each one is a compromise. Be ruthless about what you include.",
      many_stylesheets: "{stylesheets} CSS files blocking the first paint. Your users see NOTHING while your design committee loads. Make a decision and ship it.",
      some_stylesheets: "{stylesheets} stylesheets. Opportunity to consolidate.",
      many_redirects: "{redirects} redirects. The URL bounces around like a product that doesn't know what it is. Focus.",
      has_redirect: "A redirect. Make sure it's the right one. Don't ship half-measures.",
      no_hints: "No resource hints. You're not thinking about what the user needs next. Great products anticipate. Anticipate.",
      has_preload: "Preloading critical resources. You're thinking ahead. That's how you build something insanely great.",
      many_inline: "{inline} inline scripts embedded in the page. That's not engineering — that's compromising. Extract them. Optimize them. Ship something beautiful.",
    },
    summary_bad: "This isn't a product. It's a prototype that shipped too early. Go back. Start with speed. Start with the user.",
    summary_ok: "There's something here, but it's buried under compromises. Great performance, like great products, requires the courage to say no.",
    summary_good: "Fast. Clean. Focused. This page knows what it is. Now make it insanely great."
  },

  taylorswift: {
    name: "Taylor Swift",
    icon: "\u{2B50}",
    roasts: {
      slow_ttfb: "{ttfb}ms. Your server takes longer to respond than a bad date takes to text back. Not a good look.",
      medium_ttfb: "{ttfb}ms. It's fine. But fine doesn't sell out stadiums.",
      fast_ttfb: "{ttfb}ms. Quick. Clean. Like a key change that lands perfectly.",
      slow_total: "{totalTime}s. That's too long to keep someone. Trust me — I know what it's like to lose an audience's attention.",
      medium_total: "{totalTime}s. The pacing is OK. But OK songs don't become hits.",
      fast_total: "{totalTime}s. Instant. Like the first beat of a song that you just KNOW is going to be incredible.",
      huge_html: "{size}KB. Heavy. A great page, like a great song, doesn't need excess to make an impact.",
      large_html: "{size}KB. More than needed. Edit like you'd edit lyrics — every byte has to earn its place.",
      no_compression: "No compression. You're sending the extended director's cut when the radio edit would do. Compress it. Let the melody breathe.",
      has_compression: "Compressed. Clean. Like a perfectly mastered track.",
      no_cache: "No caching. Every visit is a cold open. Sometimes cold opens work. For page speed? They don't.",
      extreme_scripts: "{scripts} scripts weighing the page down. It's like overproducing a track — sometimes less instrumentation lets the melody breathe.",
      many_scripts: "{scripts} scripts. That's a lot of backing vocals. Make sure they're harmonizing, not competing.",
      many_third_party: "{thirdParty} external scripts. That's {thirdParty} features that aren't yours, telling your page how fast it can be.",
      some_third_party: "{thirdParty} external scripts. Make sure they're worth the tempo change.",
      many_stylesheets: "{stylesheets} CSS files. That's {stylesheets} costume changes before the show starts. Pick a look. Commit.",
      some_stylesheets: "{stylesheets} stylesheets. A quick change. The audience barely notices.",
      many_redirects: "{redirects} redirects. Your URL can't decide where it wants to be. I've written songs about that feeling. It's not a good one.",
      has_redirect: "A redirect. One detour. If the destination is worth it, fine.",
      no_hints: "No preload or preconnect. You're not setting up the next verse. The browser is performing without a setlist.",
      has_preload: "Preloading resources. You're cueing up the next section before the current one ends. That's professional staging.",
      many_inline: "{inline} inline scripts. They're stuck in the page like a lyric you can't get out of your head. Except this one hurts performance, not feelings.",
    },
    summary_bad: "This page is in its flop era. But every era ends. Fix the fundamentals, find your speed, and come back stronger.",
    summary_ok: "Midnights energy. There's potential, but it needs refining. The details always matter — they always do.",
    summary_good: "This is your era. Fast, clean, intentional. The performance hits and the page delivers."
  },

  kanye: {
    name: "Kanye West",
    icon: "\u{1F451}",
    roasts: {
      slow_ttfb: "{ttfb}ms. That's not ACCEPTABLE. Genius doesn't wait {ttfb}ms. Fix your server. NOW.",
      medium_ttfb: "{ttfb}ms. Mid. MID. I don't do mid. Neither should your server.",
      fast_ttfb: "{ttfb}ms. Fast. Efficient. Genius is efficient.",
      slow_total: "{totalTime}s. Time is the most valuable thing and you're WASTING IT. Every second is disrespect.",
      medium_total: "{totalTime}s. Not VISIONARY speed. Not TRASH speed. Just... speed. And just speed is NOT what we do.",
      fast_total: "{totalTime}s. FAST. That's POWER. That's VISION.",
      huge_html: "{size}KB. Bloated. The greatest things I've ever made were LEAN. Lean and POWERFUL.",
      large_html: "{size}KB. More than it needs to be. Excess without PURPOSE is just waste.",
      no_compression: "No compression. You're sending everything at full weight. That's not raw. That's not authentic. That's just HEAVY.",
      has_compression: "Compressed. CLEAN. That's the move.",
      no_cache: "No caching. The browser forgets everything. That's not living in the moment. That's AMNESIA. And amnesia is NOT a strategy.",
      extreme_scripts: "{scripts} scripts. Too much noise. Cut it down to what's ESSENTIAL. I cut entire albums down to what's essential.",
      many_scripts: "{scripts} scripts. Each one thinks it's important. They're NOT. Cut the weak ones.",
      many_third_party: "{thirdParty} external scripts telling YOUR page how fast it can be. That's letting OTHER PEOPLE define your VISION.",
      some_third_party: "{thirdParty} outside scripts. Make sure they serve YOUR vision.",
      many_stylesheets: "{stylesheets} CSS files. That's {stylesheets} things standing between the user and your VISION. Remove the barriers.",
      some_stylesheets: "{stylesheets} stylesheets. Could be leaner.",
      many_redirects: "{redirects} redirects. The URL doesn't know WHERE IT IS. I always know where I am. Your URL should too.",
      has_redirect: "A redirect. Make sure it's GOING somewhere that matters.",
      no_hints: "No resource hints. You're not PREPARING for what's next. Visionaries PREPARE.",
      has_preload: "Preloading. SMART. Thinking ahead. That's VISION.",
      many_inline: "{inline} inline scripts. Tangled up in the HTML. Can't separate them. Can't optimize them. MESSY.",
    },
    summary_bad: "This performance is BROKEN. And not in a cool deconstructed way. ACTUALLY broken. Fix it or the culture moves on without you.",
    summary_ok: "It's aight. Not VISIONARY. Not TRASH. But aight is not what we do. Push HARDER.",
    summary_good: "HARD. Fast. Clean. Powerful. This is what EXCELLENCE looks like. Respect."
  },

  zendaya: {
    name: "Zendaya",
    icon: "\u{1F31F}",
    roasts: {
      slow_ttfb: "{ttfb}ms. That's... slow. Your server should respond faster than that. People deserve a better experience.",
      medium_ttfb: "{ttfb}ms. It's OK. But 'OK' isn't what you should be aiming for.",
      fast_ttfb: "{ttfb}ms. Quick and clean. That's how it should feel.",
      slow_total: "{totalTime}s. People won't wait that long. And they shouldn't have to. Meet them where they are.",
      medium_total: "{totalTime}s. Decent. But there's room to be more intentional about speed.",
      fast_total: "{totalTime}s. Fast. Respectful of people's time. That matters.",
      huge_html: "{size}KB. That's heavy. Simplify where you can. Less is more when it's done with intention.",
      large_html: "{size}KB. A bit much. Worth trimming.",
      no_compression: "No compression. You can reduce the page size significantly with one setting change. That's an easy win.",
      has_compression: "Compressed. Clean and thoughtful.",
      no_cache: "No caching. Returning visitors download everything again. That's not a great experience for people who come back.",
      extreme_scripts: "{scripts} scripts. That's heavy. Lighter pages feel better, load better, perform better.",
      many_scripts: "{scripts} scripts. Worth auditing — not all of them are earning their place.",
      many_third_party: "{thirdParty} external scripts. That's a lot of outside influence on your page's performance. Be intentional about what you include.",
      some_third_party: "{thirdParty} external scripts. Make sure they're worth the cost.",
      many_stylesheets: "{stylesheets} CSS files blocking the first paint. People are staring at a blank screen. Let them see something sooner.",
      some_stylesheets: "{stylesheets} stylesheets. Minor optimization available.",
      many_redirects: "{redirects} redirects. That's a lot of bouncing before people get where they're going.",
      has_redirect: "A redirect. Make sure it's serving a purpose.",
      no_hints: "No resource hints. A small thing, but it shows attention to detail. Add preconnect for your critical resources.",
      has_preload: "Resource hints in place. Shows you're thinking about the full experience.",
      many_inline: "{inline} inline scripts embedded in the page. They can't be cached separately. Worth extracting.",
    },
    summary_bad: "There are some real performance issues here. But nothing unfixable. Start with compression and caching — the impact is immediate.",
    summary_ok: "Decent foundation. Some gaps, but the bones are there. Keep polishing.",
    summary_good: "Clean, fast, intentional. This is the energy. Keep it going."
  },

  chalamet: {
    name: "Timothee Chalamet",
    icon: "\u{1F3AD}",
    roasts: {
      slow_ttfb: "{ttfb}ms. The server hesitates. Like a long pause before a line. But this isn't a scene — it's a webpage. People leave during long pauses.",
      medium_ttfb: "{ttfb}ms. Not instant. Not terrible. Somewhere in between, where most things live.",
      fast_ttfb: "{ttfb}ms. Immediate. Like a cut that lands perfectly.",
      slow_total: "{totalTime}s. That's a long beat. Some beats are dramatic. This one just loses people.",
      medium_total: "{totalTime}s. It arrives. Not with urgency, but it arrives.",
      fast_total: "{totalTime}s. Clean. Immediate. Like opening a book and being immediately there.",
      huge_html: "{size}KB. Heavy. Every unnecessary weight changes how something moves through the world.",
      large_html: "{size}KB. More than it needs to be. There's probably something in there that doesn't need to exist.",
      no_compression: "No compression. The page sends everything at full size. There's no art in that — just waste.",
      has_compression: "Compressed. The essence preserved, the excess shed. Good craft.",
      no_cache: "No caching. The page forgets its visitors and they forget it. That's not the kind of impermanence that's interesting.",
      extreme_scripts: "{scripts} scripts. Heavy. Too much happening at once. The best moments have clarity.",
      many_scripts: "{scripts} scripts. Worth asking which ones are really doing something meaningful.",
      many_third_party: "{thirdParty} external scripts. Other people's code, other people's timing. You lose control of the experience.",
      some_third_party: "{thirdParty} external dependencies. Each one changes the rhythm slightly.",
      many_stylesheets: "{stylesheets} CSS files. The page hides behind them before appearing. The reveal takes too long.",
      some_stylesheets: "{stylesheets} stylesheets. A small delay before the page shows itself.",
      many_redirects: "{redirects} redirects. The URL wanders. Looking for itself, maybe. It should know where it is.",
      has_redirect: "A redirect. A moment of redirection. Sometimes necessary.",
      no_hints: "No resource hints. The browser enters each page unprepared. Preparation matters, even when it doesn't show.",
      has_preload: "Preloading. Quiet preparation. The work that happens before the scene.",
      many_inline: "{inline} inline scripts. Embedded. Inseparable. Can't be refined independently. That limits what's possible.",
    },
    summary_bad: "The page is struggling. Not with ambition — with weight. Remove the unnecessary. Speed is clarity.",
    summary_ok: "Somewhere between intention and execution. The work isn't done, but the direction is right.",
    summary_good: "Quietly fast. No excess. No performance. Just clean, honest speed."
  },

  proust: {
    name: "Marcel Proust",
    icon: "\u{1F4AD}",
    roasts: {
      slow_ttfb: "The server, having received the request, pauses — for {ttfb}ms — as if to gather its thoughts before responding, a delay that, while perhaps meaningful in the context of human correspondence, is quite unconscionable in the digital realm.",
      medium_ttfb: "{ttfb}ms — the server responds neither promptly nor disgracefully, occupying that peculiar temporal territory where one is aware of waiting but cannot quite justify complaint.",
      fast_ttfb: "{ttfb}ms — so swift that one barely registers the transition. There is something admirable in that efficiency, even if it lacks poetry.",
      slow_total: "The page materializes after {totalTime} seconds — an interval during which one experiences, in miniature, the particular anxiety of anticipated pleasure that may or may not arrive.",
      medium_total: "{totalTime}s — the page arrives with the measured pace of an afternoon at Combray. Pleasant enough, but one senses it could be swifter.",
      fast_total: "{totalTime}s. The page appears with an immediacy that leaves no room for reflection. Efficient, if perhaps somewhat brusque.",
      huge_html: "{size}KB — the HTML extends to a volume that even I, with my well-documented appreciation for length, would consider excessive.",
      large_html: "{size}KB. Substantial, though volume alone, as any reader of mine would attest, is not inherently a flaw. In HTML, however, concision is preferred.",
      no_compression: "The response arrives uncompressed, every byte transmitted in its original form — like sending the complete manuscript of In Search of Lost Time when a summary would suffice for the browser's purposes.",
      has_compression: "Compressed. The response arrives distilled, the essential preserved. Even I can appreciate brevity in transmission.",
      no_cache: "No cache headers — and so the browser, that faithful but forgetful reader, must rediscover the page entirely with each visit, unable to draw upon the involuntary memory of previous encounters.",
      extreme_scripts: "{scripts} scripts accumulate upon this page like social obligations in the month of May — each one individually reasonable, collectively exhausting.",
      many_scripts: "{scripts} scripts. A society of code, each member convinced of its own necessity.",
      many_third_party: "{thirdParty} scripts from external origins — guests from other salons, each bringing their own tempo and their own delays.",
      some_third_party: "{thirdParty} external scripts. Outside influences upon your page's temporal rhythm.",
      many_stylesheets: "{stylesheets} CSS files — each one a curtain that must be drawn before the scene is revealed, prolonging that delicious but commercially unwise moment of suspense.",
      some_stylesheets: "{stylesheets} stylesheets. A modest interval of aesthetic deliberation.",
      many_redirects: "{redirects} redirects — the URL performs a promenade through {redirects} addresses before arriving, much as one might visit several salons in an evening before reaching one's true destination.",
      has_redirect: "A redirect. A brief social call on the way to the actual page.",
      no_hints: "No resource hints — the browser enters each page as one enters an unfamiliar room, uncertain of what to expect or where to direct one's attention first.",
      has_preload: "Resource hints provided. The browser is informed in advance — a courtesy that, in both society and web performance, is always appreciated.",
      many_inline: "{inline} inline scripts, woven into the HTML like the digressions that characterize my own prose — inseparable from their context, for better or worse.",
    },
    summary_bad: "One contemplates this page's performance with the melancholy reserved for things that could have been elegant but were, through neglect, allowed to become ponderous.",
    summary_ok: "Neither triumph nor disaster — the page exists in that intermediate state where improvement is both possible and, one suspects, not unpleasant to undertake.",
    summary_good: "Admirably swift. The page arrives with an efficiency that, while perhaps lacking in romantic anticipation, demonstrates genuine technical refinement."
  },
};

const aliases = {
  musk: "elon_musk", elon: "elon_musk",
  trump: "donald_trump", donald: "donald_trump",
  altman: "sam_altman", sam: "sam_altman",
  jobs: "jobs", steve: "jobs",
  bezos: "bezos", jeff: "bezos",
  tarantino: "tarantino", quentin: "tarantino",
  nolan: "nolan", christopher: "nolan",
  reynolds: "ryanreynolds", ryan: "ryanreynolds",
  keanu: "keanureeves", reeves: "keanureeves",
  mrbeast: "mrbeast", jimmy: "mrbeast", beast: "mrbeast",
  taylor: "taylorswift", swift: "taylorswift",
  kanye: "kanye", ye: "kanye",
  zendaya: "zendaya",
  chalamet: "chalamet", timothee: "chalamet",
  billie: "billieeilish", eilish: "billieeilish",
  hemingway: "hemingway", ernest: "hemingway",
  proust: "proust", marcel: "proust",
  orwell: "orwell", george: "orwell",
  tolkien: "tolkien", jrr: "tolkien",
  nabokov: "nabokov", vladimir: "nabokov",
  christie: "christie", agatha: "christie",
  bulgakov: "bulgakov", mikhail: "bulgakov",
  dostoevsky: "dostoevsky", fyodor: "dostoevsky",
  strugatsky: "strugatsky",
  bradbury: "bradbury", ray: "bradbury",
};

function getPersona(id) {
  if (id === "random") {
    const keys = Object.keys(personas);
    return personas[keys[Math.floor(Math.random() * keys.length)]];
  }
  const resolved = aliases[id] || id;
  return personas[resolved] || null;
}

function listPersonas() {
  return Object.entries(personas).map(([id, p]) => ({
    id,
    name: p.name,
    icon: p.icon,
  }));
}

module.exports = { personas, getPersona, listPersonas };
